/* ── History Timeline Data ── */

export interface TimelineEntry {
  id: string
  date: string
  title: string
  titleEn: string
  code: string
  type: 'expansion' | 'enhanced' | 'gem-pack' | 'starter' | 'special' | 'milestone'
  description: string
  descriptionLong?: string
  image?: string
  highlight?: boolean
  cardCount?: string
  subSets?: string[]
  features?: string[]
  wikiUrl?: string
  cardImages?: string[]
}

export interface TimelineEra {
  id: string
  era: string
  eraEn: string
  period: string
  color: string
  borderColor: string
  bgColor: string
  dotColor: string
  entries: TimelineEntry[]
}

export const TIMELINE: TimelineEra[] = [
  {
    id: 'sun-moon',
    era: '太阳&月亮系列',
    eraEn: 'Sun & Moon Series',
    period: '2022.10 — 2023.09',
    color: 'text-orange-400',
    borderColor: 'border-orange-400/30',
    bgColor: 'bg-orange-400/5',
    dotColor: 'bg-orange-400',
    entries: [
      {
        id: 'sc-launch',
        date: '2022.10.28',
        title: '简体中文版正式发售',
        titleEn: 'SC Version Official Launch',
        code: '',
        type: 'milestone',
        description: '宝可梦集换式卡牌游戏简体中文版正式发售，以太阳&月亮系列作为起点。这标志着中国大陆玩家终于可以使用母语享受宝可梦TCG的乐趣。',
        descriptionLong: '2022年10月28日，宝可梦集换式卡牌游戏简体中文版正式登陆中国大陆市场。这是宝可梦TCG历史上首次以简体中文为载体发售卡牌产品，标志着中国大陆数以千万计的宝可梦爱好者终于可以使用母语收集和对战。\n\n首发以太阳&月亮系列作为起点，同时推出补充包「横空出世」三个版本和GX起始卡组，为玩家提供了完整的入门体验。\n\n简中版采用独立的卡牌编号系统（以C结尾），并且在卡池选择上与日文版和繁体中文版有所不同，形成了独特的收藏和对战生态。',
        highlight: true,
        features: ['首次简体中文正式发售', '独立编号系统（C后缀）', '太阳&月亮系列起步', 'GX机制引入'],
      },
      {
        id: 'csm1',
        date: '2022.10.28',
        title: '横空出世',
        titleEn: 'CSM1 — Debut',
        code: 'CSM1a/b/cC',
        type: 'expansion',
        description: '简中首套补充包，分为「赫」「苍」「泽」三个版本同步发售，同时推出GX起始卡组。',
        descriptionLong: '「横空出世」是简体中文版宝可梦TCG的创刊之作，同时发售三个版本：「赫」「苍」「泽」。每个版本收录不同的宝可梦和训练师卡牌，玩家可以根据喜好选择。\n\n同期发售的GX起始卡组为新手玩家提供了预组卡组，降低了入门门槛。卡牌设计延续了太阳&月亮系列的GX机制，强力的GX宝可梦成为这一时期的核心玩法。',
        image: '/images/history/sm1.png',
        cardCount: '3套补充包 + GX起始卡组',
        subSets: ['横空出世 赫（CSM1aC）', '横空出世 苍（CSM1bC）', '横空出世 泽（CSM1cC）', 'GX起始卡组（CSM1DC）'],
        features: ['GX宝可梦', '三版本同步发售', '简中首发'],
        wikiUrl: 'https://wiki.52poke.com/wiki/横空出世（简体中文）',
        cardImages: [
          '/images/cards/CSM1aC001.jpg',
          '/images/cards/CSM1aC004.jpg',
          '/images/cards/CSM1aC012.jpg',
          '/images/cards/CSM1aC013.jpg',
          '/images/cards/CSM1aC042.jpg',
          '/images/cards/CSM1aC044.jpg',
          '/images/cards/CSM1aC049.jpg',
          '/images/cards/CSM1aC055.jpg',
          '/images/cards/CSM1aC056.jpg',
          '/images/cards/CSM1aC057.jpg',
          '/images/cards/CSM1aC060.jpg',
          '/images/cards/CSM1aC062.jpg',
          '/images/cards/CSM1aC063.jpg',
          '/images/cards/CSM1aC075.jpg',
          '/images/cards/CSM1aC076.jpg',
          '/images/cards/CSM1aC077.jpg',
          '/images/cards/CSM1aC081.jpg',
          '/images/cards/CSM1aC090.jpg',
          '/images/cards/CSM1aC124.jpg',
          '/images/cards/CSM1aC125.jpg',
          '/images/cards/CSM1aC128.jpg',
          '/images/cards/CSM1aC137.jpg',
          '/images/cards/CSM1aC138.jpg',
          '/images/cards/CSM1aC140.jpg',
          '/images/cards/CSM1aC148.jpg',
          '/images/cards/CSM1aC150.jpg',
          '/images/cards/CSM1aC168.jpg',
          '/images/cards/CSM1aC169.jpg',
          '/images/cards/CSM1aC174.jpg',
          '/images/cards/CSM1aC182.jpg',
          '/images/cards/CSM1aC190.jpg',
          '/images/cards/CSM1aC202.jpg',
          '/images/cards/CSM1aC206.jpg',
          '/images/cards/CSM1aC211.jpg',
          '/images/cards/CSM1bC014.jpg',
          '/images/cards/CSM1bC030.jpg',
          '/images/cards/CSM1bC033.jpg',
          '/images/cards/CSM1bC044.jpg',
          '/images/cards/CSM1bC050.jpg',
          '/images/cards/CSM1bC060.jpg',
          '/images/cards/CSM1bC065.jpg',
          '/images/cards/CSM1bC072.jpg',
          '/images/cards/CSM1bC083.jpg',
          '/images/cards/CSM1bC091.jpg',
          '/images/cards/CSM1bC116.jpg',
          '/images/cards/CSM1bC128.jpg',
          '/images/cards/CSM1bC132.jpg',
          '/images/cards/CSM1bC133.jpg',
          '/images/cards/CSM1bC141.jpg',
          '/images/cards/CSM1bC143.jpg',
          '/images/cards/CSM1bC146.jpg',
          '/images/cards/CSM1bC147.jpg',
          '/images/cards/CSM1bC150.jpg',
          '/images/cards/CSM1bC177.jpg',
          '/images/cards/CSM1bC181.jpg',
          '/images/cards/CSM1bC188.jpg',
          '/images/cards/CSM1bC192.jpg',
          '/images/cards/CSM1bC198.jpg',
          '/images/cards/CSM1bC200.jpg',
          '/images/cards/CSM1bc104.jpg',
          '/images/cards/CSM1cC012.jpg',
          '/images/cards/CSM1cC018.jpg',
          '/images/cards/CSM1cC029.jpg',
          '/images/cards/CSM1cC050.jpg',
          '/images/cards/CSM1cC064.jpg',
          '/images/cards/CSM1cC083.jpg',
          '/images/cards/CSM1cC085.jpg',
          '/images/cards/CSM1cC101.jpg',
          '/images/cards/CSM1cC118.jpg',
          '/images/cards/CSM1cC119.jpg',
          '/images/cards/CSM1cC135.jpg',
          '/images/cards/CSM1cC136.jpg',
          '/images/cards/CSM1cC137.jpg',
          '/images/cards/CSM1cC139.jpg',
          '/images/cards/CSM1cC141.jpg',
          '/images/cards/CSM1cC144.jpg',
          '/images/cards/CSM1cC146.jpg',
          '/images/cards/CSM1cC149.jpg',
          '/images/cards/CSM1cC150.jpg',
          '/images/cards/CSM1cC178.jpg',
          '/images/cards/CSM1cC182.jpg',
          '/images/cards/CSM1cC183.jpg',
          '/images/cards/CSM1cC189.jpg',
          '/images/cards/CSM1cC200.jpg',
          '/images/cards/CSM1cC206.jpg',
          '/images/cards/CSM1cC207.jpg',
          '/images/cards/CSM1cC209.jpg',
        ],
      },
      {
        id: 'csm1-5',
        date: '2022.12.16',
        title: '对战精英',
        titleEn: 'CSM1.5 — Battle Elite',
        code: 'CSM1.5C',
        type: 'enhanced',
        description: '首个简中强化包，提供更高稀有度的卡牌。',
        descriptionLong: '「对战精英」是简体中文版的首个强化包产品。强化包相比普通补充包，收录了更多高稀有度和竞技向的卡牌，适合希望提升卡组实力的玩家。\n\n作为首个强化包，「对战精英」为简中TCG的产品线增添了多样性，让玩家有了更多选择。',
        features: ['简中首个强化包', '高稀有度卡牌'],
      },
      {
        id: 'csm2',
        date: '2023.01.18',
        title: '交相辉映',
        titleEn: 'CSM2 — Radiance',
        code: 'CSM2a/b/cC',
        type: 'expansion',
        description: '第二弹补充包，分为「沐」「魁」「唤」三个版本，继续扩充太阳&月亮卡池。',
        descriptionLong: '「交相辉映」延续了三版本发售的模式，分为「沐」「魁」「唤」三个版本。新增了大量GX宝可梦和全新的训练师卡牌，进一步丰富了简中TCG的对战环境。\n\n同步发售的GX起始卡组提供了新的预组选项，配合补充包构建更加多样化的卡组。',
        image: '/images/history/sm2.png',
        cardCount: '3套补充包 + GX起始卡组',
        subSets: ['交相辉映 沐（CSM2aC）', '交相辉映 魁（CSM2bC）', '交相辉映 唤（CSM2cC）', 'GX起始卡组（CSM2DC）'],
        features: ['三版本发售', 'GX宝可梦扩充'],
        wikiUrl: 'https://wiki.52poke.com/wiki/交相辉映（简体中文）',
        cardImages: [
          '/images/cards/CSM2aC003.jpg',
          '/images/cards/CSM2aC004.jpg',
          '/images/cards/CSM2aC009.jpg',
          '/images/cards/CSM2aC025.jpg',
          '/images/cards/CSM2aC026.jpg',
          '/images/cards/CSM2aC045.jpg',
          '/images/cards/CSM2aC054.jpg',
          '/images/cards/CSM2aC055.jpg',
          '/images/cards/CSM2aC075.jpg',
          '/images/cards/CSM2aC080.jpg',
          '/images/cards/CSM2aC090.jpg',
          '/images/cards/CSM2aC103.jpg',
          '/images/cards/CSM2aC134.jpg',
          '/images/cards/CSM2aC137.jpg',
          '/images/cards/CSM2aC138.jpg',
          '/images/cards/CSM2aC140.jpg',
          '/images/cards/CSM2aC142.jpg',
          '/images/cards/CSM2aC145.jpg',
          '/images/cards/CSM2aC147.jpg',
          '/images/cards/CSM2aC148.jpg',
          '/images/cards/CSM2aC149.jpg',
          '/images/cards/CSM2aC151.jpg',
          '/images/cards/CSM2aC152.jpg',
          '/images/cards/CSM2aC153.jpg',
          '/images/cards/CSM2aC154.jpg',
          '/images/cards/CSM2aC155.jpg',
          '/images/cards/CSM2aC157.jpg',
          '/images/cards/CSM2aC168.jpg',
          '/images/cards/CSM2bC001.jpg',
          '/images/cards/CSM2bC014.jpg',
          '/images/cards/CSM2bC017.jpg',
          '/images/cards/CSM2bC028.jpg',
          '/images/cards/CSM2bC029.jpg',
          '/images/cards/CSM2bC032.jpg',
          '/images/cards/CSM2bC033.jpg',
          '/images/cards/CSM2bC034.jpg',
          '/images/cards/CSM2bC044.jpg',
          '/images/cards/CSM2bC058.jpg',
          '/images/cards/CSM2bC062.jpg',
          '/images/cards/CSM2bC070.jpg',
          '/images/cards/CSM2bC080.jpg',
          '/images/cards/CSM2bC091.jpg',
          '/images/cards/CSM2bC120.jpg',
          '/images/cards/CSM2bC129.jpg',
          '/images/cards/CSM2bC130.jpg',
          '/images/cards/CSM2bC131.jpg',
          '/images/cards/CSM2bC132.jpg',
          '/images/cards/CSM2bC133.jpg',
          '/images/cards/CSM2bC136.jpg',
          '/images/cards/CSM2bC137.jpg',
          '/images/cards/CSM2bC138.jpg',
          '/images/cards/CSM2bC139.jpg',
          '/images/cards/CSM2bC145.jpg',
          '/images/cards/CSM2bC147.jpg',
          '/images/cards/CSM2bC149.jpg',
          '/images/cards/CSM2bC151.jpg',
          '/images/cards/CSM2bC152.jpg',
          '/images/cards/CSM2bC154.jpg',
          '/images/cards/CSM2bC161.jpg',
          '/images/cards/CSM2bC179.jpg',
          '/images/cards/CSM2cC001.jpg',
          '/images/cards/CSM2cC021.jpg',
          '/images/cards/CSM2cC045.jpg',
          '/images/cards/CSM2cC050.jpg',
          '/images/cards/CSM2cC063.jpg',
          '/images/cards/CSM2cC088.jpg',
          '/images/cards/CSM2cC103.jpg',
          '/images/cards/CSM2cC104.jpg',
          '/images/cards/CSM2cC109.jpg',
          '/images/cards/CSM2cC131.jpg',
          '/images/cards/CSM2cC132.jpg',
          '/images/cards/CSM2cC134.jpg',
          '/images/cards/CSM2cC139.jpg',
          '/images/cards/CSM2cC145.jpg',
          '/images/cards/CSM2cC146.jpg',
          '/images/cards/CSM2cC147.jpg',
          '/images/cards/CSM2cC149.jpg',
          '/images/cards/CSM2cC151.jpg',
          '/images/cards/CSM2cC152.jpg',
          '/images/cards/CSM2cC173.jpg',
        ],
      },
      {
        id: 'csm2-5',
        date: '2023.03.17',
        title: '炫奇争胜',
        titleEn: 'CSM2.5 — Spectacular Victory',
        code: 'CSM2.5C',
        type: 'enhanced',
        description: '太阳&月亮系列第二个强化包。',
        descriptionLong: '「炫奇争胜」是太阳&月亮系列的第二个强化包，收录了来自多个系列的精选卡牌，提供了独特的收藏和对战价值。',
        features: ['精选高稀有度卡牌'],
      },
      {
        id: 'csm2-1',
        date: '2023.09.09',
        title: '辉金能量专题包',
        titleEn: 'CSM2.1 — Shining Gold Energy',
        code: 'CSM2.1C',
        type: 'special',
        description: '太阳&月亮系列收官之作，辉金能量专题包。',
        descriptionLong: '「辉金能量专题包」是太阳&月亮系列在简中版的收官之作。专题包以特殊能量卡和辉金配色为特点，为这一系列画上了华丽的句号。\n\n在此之后，简中版正式进入剑&盾系列时代。',
        features: ['太阳&月亮收官', '特殊能量卡牌', '辉金配色'],
      },
    ],
  },
  {
    id: 'sword-shield',
    era: '剑&盾系列',
    eraEn: 'Sword & Shield Series',
    period: '2023.05 — 2024.11',
    color: 'text-cyan-400',
    borderColor: 'border-cyan-400/30',
    bgColor: 'bg-cyan-400/5',
    dotColor: 'bg-cyan-400',
    entries: [
      {
        id: 'cs1',
        date: '2023.05.19',
        title: '极巨争锋',
        titleEn: 'CS1 — Dynamax Showdown',
        code: 'CS1a/bC',
        type: 'expansion',
        description: '剑&盾系列首弹。「雷」「焰」双版本发售，引入V机制和极巨化系统。',
        descriptionLong: '「极巨争锋」标志着简中TCG进入全新的剑&盾时代。采用双版本发售模式（「雷」「焰」），引入了V宝可梦和VMAX极巨化机制。\n\n极巨化系统带来了前所未有的高HP宝可梦卡牌，改变了对战格局。同步推出的V起始卡组让新玩家也能快速融入新系列。\n\n剑&盾系列是简中TCG发展最快的时期，产品线快速扩展，市场规模显著增长。',
        image: '/images/history/ss1.png',
        cardCount: '2套补充包 + V起始卡组',
        subSets: ['极巨争锋 雷（CS1aC）', '极巨争锋 焰（CS1bC）', 'V起始卡组（CS1DC）'],
        features: ['V宝可梦引入', 'VMAX极巨化机制', '双版本发售'],
        wikiUrl: 'https://wiki.52poke.com/wiki/极巨争锋（简体中文）',
        cardImages: [
          '/images/cards/CS1aC018.jpg',
          '/images/cards/CS1aC028.jpg',
          '/images/cards/CS1aC029.jpg',
          '/images/cards/CS1aC031.jpg',
          '/images/cards/CS1aC120.jpg',
          '/images/cards/CS1aC125.jpg',
          '/images/cards/CS1aC131.jpg',
          '/images/cards/CS1aC132.jpg',
          '/images/cards/CS1aC135.jpg',
          '/images/cards/CS1aC161.jpg',
          '/images/cards/CS1aC165.jpg',
          '/images/cards/CS1aC181.jpg',
          '/images/cards/CS1aC192.jpg',
          '/images/cards/CS1aC194.jpg',
          '/images/cards/CS1aC195.jpg',
          '/images/cards/CS1aC211.jpg',
          '/images/cards/CS1aC212.jpg',
          '/images/cards/CS1aC217.jpg',
          '/images/cards/CS1ac019.jpg',
          '/images/cards/CS1bC030.jpg',
          '/images/cards/CS1bC031.jpg',
          '/images/cards/CS1bC049.jpg',
          '/images/cards/CS1bC050.jpg',
          '/images/cards/CS1bC051.jpg',
          '/images/cards/CS1bC122.jpg',
          '/images/cards/CS1bC125.jpg',
          '/images/cards/CS1bC128.jpg',
          '/images/cards/CS1bC129.jpg',
          '/images/cards/CS1bC132.jpg',
          '/images/cards/CS1bC134.jpg',
          '/images/cards/CS1bC145.jpg',
          '/images/cards/CS1bC155.jpg',
          '/images/cards/CS1bC170.jpg',
          '/images/cards/CS1bC175.jpg',
          '/images/cards/CS1bC181.jpg',
          '/images/cards/CS1bC182.jpg',
          '/images/cards/CS1bC189.jpg',
          '/images/cards/CS1bC191.jpg',
          '/images/cards/CS1bC194.jpg',
        ],
      },
      {
        id: 'cs1-5',
        date: '2023.06.28',
        title: '极巨攻防',
        titleEn: 'CS1.5 — Dynamax Offense & Defense',
        code: 'CS1.5C',
        type: 'enhanced',
        description: '首个剑&盾强化包。',
        descriptionLong: '「极巨攻防」是剑&盾系列的首个强化包，收录了竞技向的V和VMAX卡牌，强化了对战环境的多样性。',
        features: ['剑&盾首个强化包', 'VMAX强化'],
      },
      {
        id: 'cs2',
        date: '2023.08.18',
        title: '浓墨重彩',
        titleEn: 'CS2 — Vivid Colors',
        code: 'CS2a/bC',
        type: 'expansion',
        description: '「黎」「靛」双版本，继续扩充剑&盾卡池。',
        descriptionLong: '「浓墨重彩」以「黎」「靛」双版本发售，进一步扩充了剑&盾系列的卡牌阵容。新增了多种V和VMAX宝可梦，为对战环境带来新的策略选择。',
        image: '/images/history/ss2.png',
        subSets: ['浓墨重彩 黎（CS2aC）', '浓墨重彩 靛（CS2bC）'],
        features: ['双版本', 'V/VMAX扩充'],
        cardImages: [
          '/images/cards/CS2aC020.jpg',
          '/images/cards/CS2aC022.jpg',
          '/images/cards/CS2aC026.jpg',
          '/images/cards/CS2aC037.jpg',
          '/images/cards/CS2aC062.jpg',
          '/images/cards/CS2aC065.jpg',
          '/images/cards/CS2aC093.jpg',
          '/images/cards/CS2aC106.jpg',
          '/images/cards/CS2aC108.jpg',
          '/images/cards/CS2aC110.jpg',
          '/images/cards/CS2aC113.jpg',
          '/images/cards/CS2aC114.jpg',
          '/images/cards/CS2aC131.jpg',
          '/images/cards/CS2aC133.jpg',
          '/images/cards/CS2aC134.jpg',
          '/images/cards/CS2aC143.jpg',
          '/images/cards/CS2bC006.jpg',
          '/images/cards/CS2bC021.jpg',
          '/images/cards/CS2bC022.jpg',
          '/images/cards/CS2bC028.jpg',
          '/images/cards/CS2bC070.jpg',
          '/images/cards/CS2bC071.jpg',
          '/images/cards/CS2bC074.jpg',
          '/images/cards/CS2bC099.jpg',
          '/images/cards/CS2bC103.jpg',
          '/images/cards/CS2bC110.jpg',
          '/images/cards/CS2bC112.jpg',
          '/images/cards/CS2bC113.jpg',
          '/images/cards/CS2bC115.jpg',
          '/images/cards/CS2bC132.jpg',
          '/images/cards/CS2bC136.jpg',
          '/images/cards/CS2bC143.jpg',
        ],
      },
      {
        id: 'cs2-5',
        date: '2023.09.29',
        title: '璀璨反击',
        titleEn: 'CS2.5 — Brilliant Counter',
        code: 'CS2.5C',
        type: 'enhanced',
        description: '高稀有度强化包。',
        descriptionLong: '「璀璨反击」以高稀有度卡牌为特色的强化包，收录了大量CHR、CSR等特殊稀有度的插画卡牌，深受收藏家喜爱。',
        features: ['高稀有度特色', 'CHR/CSR插画卡'],
      },
      {
        id: 'cs3',
        date: '2023.11.17',
        title: '洪荒演武',
        titleEn: 'CS3 — Primal Martial',
        code: 'CS3a/bC',
        type: 'expansion',
        description: '「茂」「激」双版本，V起始卡组同步发售。',
        descriptionLong: '「洪荒演武」以「茂」「激」双版本发售，V起始卡组同步推出。本弹引入了更多元化的对战策略，新增了VSTAR机制的强力宝可梦。',
        image: '/images/history/ss3.png',
        subSets: ['洪荒演武 茂（CS3aC）', '洪荒演武 激（CS3bC）', 'V起始卡组（CS3DC）'],
        features: ['VSTAR机制', '双版本 + 起始卡组'],
        cardImages: [
          '/images/cards/CS3aC035.jpg',
          '/images/cards/CS3aC043.jpg',
          '/images/cards/CS3aC054.jpg',
          '/images/cards/CS3aC055.jpg',
          '/images/cards/CS3aC060.jpg',
          '/images/cards/CS3aC063.jpg',
          '/images/cards/CS3aC071.jpg',
          '/images/cards/CS3aC072.jpg',
          '/images/cards/CS3aC085.jpg',
          '/images/cards/CS3aC086.jpg',
          '/images/cards/CS3aC094.jpg',
          '/images/cards/CS3aC097.jpg',
          '/images/cards/CS3aC107.jpg',
          '/images/cards/CS3aC112.jpg',
          '/images/cards/CS3aC116.jpg',
          '/images/cards/CS3aC121.jpg',
          '/images/cards/CS3aC122.jpg',
          '/images/cards/CS3aC123.jpg',
          '/images/cards/CS3aC125.jpg',
          '/images/cards/CS3aC127.jpg',
          '/images/cards/CS3aC128.jpg',
          '/images/cards/CS3aC130.jpg',
          '/images/cards/CS3aC132.jpg',
          '/images/cards/CS3aC151.jpg',
          '/images/cards/CS3aC155.jpg',
          '/images/cards/CS3aC158.jpg',
          '/images/cards/CS3aC167.jpg',
          '/images/cards/CS3aC182.jpg',
          '/images/cards/CS3bC031.jpg',
          '/images/cards/CS3bC036.jpg',
          '/images/cards/CS3bC044.jpg',
          '/images/cards/CS3bC045.jpg',
          '/images/cards/CS3bC058.jpg',
          '/images/cards/CS3bC061.jpg',
          '/images/cards/CS3bC065.jpg',
          '/images/cards/CS3bC079.jpg',
          '/images/cards/CS3bC084.jpg',
          '/images/cards/CS3bC085.jpg',
          '/images/cards/CS3bC086.jpg',
          '/images/cards/CS3bC100.jpg',
          '/images/cards/CS3bC104.jpg',
          '/images/cards/CS3bC105.jpg',
          '/images/cards/CS3bC116.jpg',
          '/images/cards/CS3bC118.jpg',
          '/images/cards/CS3bC119.jpg',
          '/images/cards/CS3bC121.jpg',
          '/images/cards/CS3bC122.jpg',
          '/images/cards/CS3bC124.jpg',
          '/images/cards/CS3bC126.jpg',
          '/images/cards/CS3bC129.jpg',
          '/images/cards/CS3bC138.jpg',
          '/images/cards/CS3bC149.jpg',
          '/images/cards/CS3bC152.jpg',
          '/images/cards/CS3bC155.jpg',
          '/images/cards/CS3bC165.jpg',
          '/images/cards/CS3bC177.jpg',
        ],
      },
      {
        id: 'cs3-5',
        date: '2024.01.05',
        title: '怒炎灼天',
        titleEn: 'CS3.5 — Blazing Sky',
        code: 'CS3.5C',
        type: 'enhanced',
        description: '强化包。',
        descriptionLong: '「怒炎灼天」是一款以火属性宝可梦为主打的强化包，收录了大量火系V和VMAX卡牌。',
        features: ['火属性主题'],
      },
      {
        id: 'cs4',
        date: '2024.03.01',
        title: '九彩汇聚',
        titleEn: 'CS4 — Nine Colors',
        code: 'CS4a/bC',
        type: 'expansion',
        description: '「朋」「源」双版本。',
        descriptionLong: '「九彩汇聚」以「朋」「源」双版本发售，名称寓意九种属性的汇聚，收录了覆盖全属性的强力宝可梦。',
        image: '/images/history/ss4.png',
        subSets: ['九彩汇聚 朋（CS4aC）', '九彩汇聚 源（CS4bC）'],
        features: ['全属性覆盖', '双版本'],
        cardImages: [
          '/images/cards/CS4aC003.jpg',
          '/images/cards/CS4aC009.jpg',
          '/images/cards/CS4aC020.jpg',
          '/images/cards/CS4aC026.jpg',
          '/images/cards/CS4aC035.jpg',
          '/images/cards/CS4aC048.jpg',
          '/images/cards/CS4aC049.jpg',
          '/images/cards/CS4aC059.jpg',
          '/images/cards/CS4aC067.jpg',
          '/images/cards/CS4aC085.jpg',
          '/images/cards/CS4aC094.jpg',
          '/images/cards/CS4aC106.jpg',
          '/images/cards/CS4aC107.jpg',
          '/images/cards/CS4aC111.jpg',
          '/images/cards/CS4aC118.jpg',
          '/images/cards/CS4aC120.jpg',
          '/images/cards/CS4aC124.jpg',
          '/images/cards/CS4aC125.jpg',
          '/images/cards/CS4aC130.jpg',
          '/images/cards/CS4aC131.jpg',
          '/images/cards/CS4aC132.jpg',
          '/images/cards/CS4aC155.jpg',
          '/images/cards/CS4aC164.jpg',
          '/images/cards/CS4aC166.jpg',
          '/images/cards/CS4aC182.jpg',
          '/images/cards/CS4bC030.jpg',
          '/images/cards/CS4bC031.jpg',
          '/images/cards/CS4bC032.jpg',
          '/images/cards/CS4bC048.jpg',
          '/images/cards/CS4bC049.jpg',
          '/images/cards/CS4bC058.jpg',
          '/images/cards/CS4bC085.jpg',
          '/images/cards/CS4bC097.jpg',
          '/images/cards/CS4bC098.jpg',
          '/images/cards/CS4bC106.jpg',
          '/images/cards/CS4bC117.jpg',
          '/images/cards/CS4bC118.jpg',
          '/images/cards/CS4bC127.jpg',
          '/images/cards/CS4bC129.jpg',
          '/images/cards/CS4bC130.jpg',
          '/images/cards/CS4bC132.jpg',
          '/images/cards/CS4bC154.jpg',
          '/images/cards/CS4bC156.jpg',
          '/images/cards/CS4bC175.jpg',
        ],
      },
      {
        id: 'cs4-5',
        date: '2024.04.26',
        title: '终末炎舞',
        titleEn: 'CS4.5 — Final Blaze Dance',
        code: 'CS4.5C',
        type: 'enhanced',
        description: '强化包。',
        descriptionLong: '「终末炎舞」是一款强化包，为中期剑&盾对战环境增添了新选项。',
        features: ['强化包'],
      },
      {
        id: 'cs5',
        date: '2024.06.18',
        title: '勇魅群星',
        titleEn: 'CS5 — Brave Stars',
        code: 'CS5a/bC',
        type: 'expansion',
        description: '「魅」「勇」双版本，V起始卡组同步发售。',
        descriptionLong: '「勇魅群星」以「魅」「勇」双版本发售，V起始卡组同步推出。本弹收录了大量人气宝可梦的新卡牌，是剑&盾后期的重要补充包。',
        image: '/images/history/ss5.png',
        subSets: ['勇魅群星 魅（CS5aC）', '勇魅群星 勇（CS5bC）', 'V起始卡组（CS5DC）'],
        features: ['人气宝可梦', '双版本 + 起始卡组'],
        cardImages: [
          '/images/cards/CS5aC014.jpg',
          '/images/cards/CS5aC049.jpg',
          '/images/cards/CS5aC063.jpg',
          '/images/cards/CS5aC074.jpg',
          '/images/cards/CS5aC079.jpg',
          '/images/cards/CS5aC105.jpg',
          '/images/cards/CS5aC106.jpg',
          '/images/cards/CS5aC107.jpg',
          '/images/cards/CS5aC115.jpg',
          '/images/cards/CS5aC118.jpg',
          '/images/cards/CS5aC120.jpg',
          '/images/cards/CS5aC121.jpg',
          '/images/cards/CS5aC126.jpg',
          '/images/cards/CS5aC127.jpg',
          '/images/cards/CS5aC128.jpg',
          '/images/cards/CS5aC129.jpg',
          '/images/cards/CS5aC130.jpg',
          '/images/cards/CS5aC157.jpg',
          '/images/cards/CS5bC049.jpg',
          '/images/cards/CS5bC050.jpg',
          '/images/cards/CS5bC051.jpg',
          '/images/cards/CS5bC052.jpg',
          '/images/cards/CS5bC054.jpg',
          '/images/cards/CS5bC080.jpg',
          '/images/cards/CS5bC087.jpg',
          '/images/cards/CS5bC088.jpg',
          '/images/cards/CS5bC095.jpg',
          '/images/cards/CS5bC096.jpg',
          '/images/cards/CS5bC113.jpg',
          '/images/cards/CS5bC116.jpg',
          '/images/cards/CS5bC119.jpg',
          '/images/cards/CS5bC130.jpg',
          '/images/cards/CS5bC131.jpg',
          '/images/cards/CS5bC156.jpg',
          '/images/cards/CS5bC157.jpg',
          '/images/cards/CS5bC158.jpg',
        ],
      },
      {
        id: 'cs5-5',
        date: '2024.08.02',
        title: '暗影夺辉',
        titleEn: 'CS5.5 — Shadow Shine',
        code: 'CS5.5C',
        type: 'enhanced',
        description: '强化包。',
        descriptionLong: '「暗影夺辉」是一款以暗属性和超属性为主题的强化包。',
        features: ['暗/超属性主题'],
      },
      {
        id: 'cs6',
        date: '2024.09.20',
        title: '碧海暗影',
        titleEn: 'CS6 — Ocean Shadow',
        code: 'CS6a/bC',
        type: 'expansion',
        description: '「啸」「逐」双版本。',
        descriptionLong: '「碧海暗影」以「啸」「逐」双版本发售，是剑&盾系列的最后一套主要补充包，收录了该系列最终阵容的强力宝可梦。',
        image: '/images/history/ss6.png',
        subSets: ['碧海暗影 啸（CS6aC）', '碧海暗影 逐（CS6bC）'],
        features: ['剑&盾后期', '双版本'],
        cardImages: [
          '/images/cards/CS6aC011.jpg',
          '/images/cards/CS6aC020.jpg',
          '/images/cards/CS6aC024.jpg',
          '/images/cards/CS6aC027.jpg',
          '/images/cards/CS6aC036.jpg',
          '/images/cards/CS6aC056.jpg',
          '/images/cards/CS6aC065.jpg',
          '/images/cards/CS6aC070.jpg',
          '/images/cards/CS6aC086.jpg',
          '/images/cards/CS6aC094.jpg',
          '/images/cards/CS6aC097.jpg',
          '/images/cards/CS6aC099.jpg',
          '/images/cards/CS6aC101.jpg',
          '/images/cards/CS6aC103.jpg',
          '/images/cards/CS6aC113.jpg',
          '/images/cards/CS6aC120.jpg',
          '/images/cards/CS6aC125.jpg',
          '/images/cards/CS6aC126.jpg',
          '/images/cards/CS6aC129.jpg',
          '/images/cards/CS6aC130.jpg',
          '/images/cards/CS6aC131.jpg',
          '/images/cards/CS6bC011.jpg',
          '/images/cards/CS6bC012.jpg',
          '/images/cards/CS6bC013.jpg',
          '/images/cards/CS6bC023.jpg',
          '/images/cards/CS6bC026.jpg',
          '/images/cards/CS6bC028.jpg',
          '/images/cards/CS6bC037.jpg',
          '/images/cards/CS6bC039.jpg',
          '/images/cards/CS6bC048.jpg',
          '/images/cards/CS6bC052.jpg',
          '/images/cards/CS6bC067.jpg',
          '/images/cards/CS6bC068.jpg',
          '/images/cards/CS6bC074.jpg',
          '/images/cards/CS6bC084.jpg',
          '/images/cards/CS6bC107.jpg',
          '/images/cards/CS6bC108.jpg',
          '/images/cards/CS6bC123.jpg',
          '/images/cards/CS6bC125.jpg',
          '/images/cards/CS6bC128.jpg',
          '/images/cards/CS6bC130.jpg',
          '/images/cards/CS6bC132.jpg',
          '/images/cards/CS6bC135.jpg',
          '/images/cards/CS6bC158.jpg',
          '/images/cards/CS6bC170.jpg',
        ],
      },
      {
        id: 'cs6-5',
        date: '2024.11.15',
        title: '胜象星引',
        titleEn: 'CS6.5 — Victory Star Guide',
        code: 'CS6.5C',
        type: 'enhanced',
        description: '剑&盾系列收官强化包。',
        descriptionLong: '「胜象星引」是剑&盾系列在简中版的收官之作。收录了整个系列的精华卡牌，为剑&盾时代画上圆满的句号。\n\n在此之后，简中版正式进入全新的朱&紫系列时代。',
        features: ['剑&盾收官', '系列精华'],
      },
    ],
  },
  {
    id: 'scarlet-violet',
    era: '朱&紫系列',
    eraEn: 'Scarlet & Violet Series',
    period: '2025.01 — 现在',
    color: 'text-violet-400',
    borderColor: 'border-violet-400/30',
    bgColor: 'bg-violet-400/5',
    dotColor: 'bg-violet-400',
    entries: [
      {
        id: 'sv-launch',
        date: '2025.01.17',
        title: '朱&紫系列启动 · 多线齐发',
        titleEn: 'SV Series Launch — Multi-Line Debut',
        code: '',
        type: 'milestone',
        description: '简中宝可梦TCG迎来全新时代。朱&紫系列、宝石包、收集啦151三条产品线同日启动，展现了简中市场的快速成长。',
        descriptionLong: '2025年1月17日，简中宝可梦TCG迎来了历史性的一天——三条产品线同日启动：\n\n1. 朱&紫主系列补充包「亘古开来」\n2. 简中独占收藏线「宝石包 VOL.1」\n3. 人气企划「收集啦151 旅」\n\n这一天的多线齐发展现了简中TCG市场的成熟度和The Pokémon Company对中国大陆市场的重视。朱&紫系列引入了全新的ex机制和太晶化系统，为对战环境带来了革命性的变化。\n\n宝石包作为简中独占的收藏型产品线，以精美的闪卡和独特的编号系统吸引了大量收藏家。',
        highlight: true,
        features: ['三线齐发', 'ex机制引入', '太晶化系统', '宝石包独占线'],
      },
      {
        id: 'csv1',
        date: '2025.01.17',
        title: '亘古开来',
        titleEn: 'CSV1 — Ancient Future',
        code: 'CSV1C',
        type: 'expansion',
        description: '朱&紫系列首弹补充包，引入全新G规则标记和ex机制，127+40张卡牌。',
        descriptionLong: '「亘古开来」是朱&紫系列在简中版的首弹补充包。引入了全新的G规则标记和ex机制，收录127张基础卡牌和40张特殊卡牌，共计167张。\n\nex机制取代了前作的V/VMAX系统，ex宝可梦具有强力的技能但被击倒时对手可获得2张奖赏卡。新的太晶化系统允许宝可梦改变属性，增加了策略深度。',
        image: '/images/history/sv1.png',
        cardCount: '127+40',
        features: ['ex机制首次登场', 'G规则标记', '太晶化系统', '167张卡牌'],
        wikiUrl: 'https://wiki.52poke.com/wiki/亘古开来（简体中文）',
        cardImages: [
          '/images/cards/CSV1C009.jpg',
          '/images/cards/CSV1C024.jpg',
          '/images/cards/CSV1C029.jpg',
          '/images/cards/CSV1C035.jpg',
          '/images/cards/CSV1C037.jpg',
          '/images/cards/CSV1C067.jpg',
          '/images/cards/CSV1C068.jpg',
          '/images/cards/CSV1C084.jpg',
          '/images/cards/CSV1C086.jpg',
          '/images/cards/CSV1C092.jpg',
          '/images/cards/CSV1C096.jpg',
          '/images/cards/CSV1C103.jpg',
          '/images/cards/CSV1C105.jpg',
          '/images/cards/CSV1C118.jpg',
          '/images/cards/CSV1C119.jpg',
          '/images/cards/CSV1C122.jpg',
          '/images/cards/CSV1C126.jpg',
          '/images/cards/CSV1C128.jpg',
          '/images/cards/CSV1C129.jpg',
          '/images/cards/CSV1C130.jpg',
          '/images/cards/CSV1C132.jpg',
          '/images/cards/CSV1C133.jpg',
          '/images/cards/CSV1C134.jpg',
          '/images/cards/CSV1C135.jpg',
          '/images/cards/CSV1C136.jpg',
          '/images/cards/CSV1C137.jpg',
          '/images/cards/CSV1C138.jpg',
          '/images/cards/CSV1C139.jpg',
          '/images/cards/CSV1C140.jpg',
          '/images/cards/CSV1C141.jpg',
          '/images/cards/CSV1C142.jpg',
          '/images/cards/CSV1C143.jpg',
          '/images/cards/CSV1C144.jpg',
          '/images/cards/CSV1C145.jpg',
          '/images/cards/CSV1C147.jpg',
          '/images/cards/CSV1C148.jpg',
          '/images/cards/CSV1C149.jpg',
          '/images/cards/CSV1C150.jpg',
          '/images/cards/CSV1C151.jpg',
          '/images/cards/CSV1C152.jpg',
          '/images/cards/CSV1C153.jpg',
          '/images/cards/CSV1C154.jpg',
          '/images/cards/CSV1C155.jpg',
          '/images/cards/CSV1C156.jpg',
          '/images/cards/CSV1C157.jpg',
          '/images/cards/CSV1C158.jpg',
          '/images/cards/CSV1C159.jpg',
          '/images/cards/CSV1C160.jpg',
          '/images/cards/CSV1C161.jpg',
          '/images/cards/CSV1C162.jpg',
          '/images/cards/CSV1C163.jpg',
          '/images/cards/CSV1C164.jpg',
          '/images/cards/CSV1C165.jpg',
        ],
      },
      {
        id: 'gem-pack-1',
        date: '2025.01.17',
        title: '宝石包 VOL.1',
        titleEn: 'Gem Pack VOL.1',
        code: 'CBB1C',
        type: 'gem-pack',
        description: '简中独占的收藏型产品线「宝石包」首弹。以高品质闪卡和独特编号系统为卖点，115张卡牌。',
        descriptionLong: '宝石包（Gem Pack）是简体中文版独占的收藏型产品线，不同于主系列的补充包。宝石包以收藏价值为核心，每张卡牌都采用特殊工艺制作，具有独特的闪光效果。\n\n宝石包 VOL.1 收录115张卡牌，采用独立的CBB编号系统。每包含有多张不同闪光工艺的卡牌，包括AR（Art Rare）、SR（Super Rare）等稀有度。\n\n宝石包的推出立即在收藏市场引起轰动，部分高稀有度卡牌的二级市场价格远超发行价。',
        image: '/images/poster-vol1-square.png',
        cardCount: '115',
        highlight: true,
        features: ['简中独占产品线', 'CBB编号系统', '全闪卡设计', '高收藏价值'],
        cardImages: [
          '/images/cards/CBB1C0106.jpg',
          '/images/cards/CBB1C0108.jpg',
          '/images/cards/CBB1C0109.jpg',
          '/images/cards/CBB1C0309.jpg',
          '/images/cards/CBB1C0509.jpg',
          '/images/cards/CBB1C0705.jpg',
          '/images/cards/CBB1C0706.jpg',
          '/images/cards/CBB1C0708.jpg',
          '/images/cards/CBB1C0709.jpg',
        ],
      },
      {
        id: 'csv2',
        date: '2025.03.21',
        title: '奇迹启程',
        titleEn: 'CSV2 — Miracle Journey',
        code: 'CSV2C',
        type: 'expansion',
        description: '朱&紫第二弹补充包，128+35张卡牌。',
        descriptionLong: '「奇迹启程」是朱&紫系列的第二弹补充包，收录了128张基础卡牌和35张特殊卡牌。延续了ex和太晶化机制，新增了更多帕底亚地区的宝可梦。',
        image: '/images/history/sv2.png',
        cardCount: '128+35',
        features: ['帕底亚宝可梦扩充', 'ex机制深化'],
        cardImages: [
          '/images/cards/CSV2C012.jpg',
          '/images/cards/CSV2C018.jpg',
          '/images/cards/CSV2C021.jpg',
          '/images/cards/CSV2C033.jpg',
          '/images/cards/CSV2C053.jpg',
          '/images/cards/CSV2C054.jpg',
          '/images/cards/CSV2C055.jpg',
          '/images/cards/CSV2C085.jpg',
          '/images/cards/CSV2C107.jpg',
          '/images/cards/CSV2C111.jpg',
          '/images/cards/CSV2C114.jpg',
          '/images/cards/CSV2C118.jpg',
          '/images/cards/CSV2C127.jpg',
          '/images/cards/CSV2C132.jpg',
          '/images/cards/CSV2C133.jpg',
          '/images/cards/CSV2C145.jpg',
          '/images/cards/CSV2C148.jpg',
          '/images/cards/CSV2C155.jpg',
          '/images/cards/CSV2C163.jpg',
        ],
      },
      {
        id: 'csv3',
        date: '2025.05.16',
        title: '无畏太晶',
        titleEn: 'CSV3 — Fearless Tera',
        code: 'CSV3C',
        type: 'expansion',
        description: '朱&紫第三弹补充包，130+35张卡牌。',
        descriptionLong: '「无畏太晶」以太晶化为主题，收录了130+35张卡牌。大量宝可梦获得了太晶化形态，展现了不同属性的太晶化变化。',
        image: '/images/history/sv3.png',
        cardCount: '130+35',
        features: ['太晶化主题', '属性变化策略'],
        cardImages: [
          '/images/cards/CSV3C001.jpg',
          '/images/cards/CSV3C018.jpg',
          '/images/cards/CSV3C031.jpg',
          '/images/cards/CSV3C040.jpg',
          '/images/cards/CSV3C041.jpg',
          '/images/cards/CSV3C042.jpg',
          '/images/cards/CSV3C043.jpg',
          '/images/cards/CSV3C044.jpg',
          '/images/cards/CSV3C095.jpg',
          '/images/cards/CSV3C097.jpg',
          '/images/cards/CSV3C115.jpg',
          '/images/cards/CSV3C119.jpg',
          '/images/cards/CSV3C121.jpg',
          '/images/cards/CSV3C125.jpg',
          '/images/cards/CSV3C128.jpg',
          '/images/cards/CSV3C129.jpg',
          '/images/cards/CSV3C131.jpg',
          '/images/cards/CSV3C132.jpg',
          '/images/cards/CSV3C133.jpg',
          '/images/cards/CSV3C136.jpg',
          '/images/cards/CSV3C137.jpg',
          '/images/cards/CSV3C144.jpg',
          '/images/cards/CSV3C149.jpg',
          '/images/cards/CSV3C155.jpg',
          '/images/cards/CSV3C156.jpg',
        ],
      },
      {
        id: 'gem-pack-2',
        date: '2025.05.16',
        title: '宝石包 VOL.2',
        titleEn: 'Gem Pack VOL.2',
        code: 'CBB2C',
        type: 'gem-pack',
        description: '宝石包第二弹，约144张卡牌。',
        descriptionLong: '宝石包 VOL.2 延续了首弹的高品质路线，收录约144张全闪卡牌。新增了更多热门宝可梦的AR和SR版本，包括仙子伊布、伊布等人气角色的精美插画卡牌。',
        image: '/images/poster-vol2-square.png',
        cardCount: '~144',
        features: ['人气宝可梦AR', '仙子伊布收录', '闪卡扩充'],
        cardImages: [
          '/images/cards/CBB2C0115.jpg',
          '/images/cards/CBB2C0615.jpg',
          '/images/cards/CBB2C0715.jpg',
          '/images/cards/CBB2C0915.jpg',
        ],
      },
      {
        id: 'csv4',
        date: '2025.07.18',
        title: '嘉奖回合',
        titleEn: 'CSV4 — Prize Round',
        code: 'CSV4C',
        type: 'expansion',
        description: '朱&紫第四弹补充包，129+36张卡牌。',
        descriptionLong: '「嘉奖回合」是朱&紫第四弹，收录129+36张卡牌。以奖赏机制为主题，引入了与奖赏卡互动的新策略。',
        image: '/images/history/sv4.png',
        cardCount: '129+36',
        features: ['奖赏卡互动', '新策略引入'],
        cardImages: [
          '/images/cards/CSV4C008.jpg',
          '/images/cards/CSV4C029.jpg',
          '/images/cards/CSV4C030.jpg',
          '/images/cards/CSV4C039.jpg',
          '/images/cards/CSV4C047.jpg',
          '/images/cards/CSV4C077.jpg',
          '/images/cards/CSV4C088.jpg',
          '/images/cards/CSV4C089.jpg',
          '/images/cards/CSV4C101.jpg',
          '/images/cards/CSV4C113.jpg',
          '/images/cards/CSV4C114.jpg',
          '/images/cards/CSV4C119.jpg',
          '/images/cards/CSV4C120.jpg',
          '/images/cards/CSV4C121.jpg',
          '/images/cards/CSV4C122.jpg',
          '/images/cards/CSV4C126.jpg',
          '/images/cards/CSV4C127.jpg',
          '/images/cards/CSV4C128.jpg',
          '/images/cards/CSV4C129.jpg',
          '/images/cards/CSV4C132.jpg',
          '/images/cards/CSV4C133.jpg',
          '/images/cards/CSV4C135.jpg',
          '/images/cards/CSV4C136.jpg',
          '/images/cards/CSV4C137.jpg',
          '/images/cards/CSV4C141.jpg',
          '/images/cards/CSV4C147.jpg',
          '/images/cards/CSV4C149.jpg',
          '/images/cards/CSV4C156.jpg',
          '/images/cards/CSV4C157.jpg',
          '/images/cards/CSV4C158.jpg',
          '/images/cards/CSV4C159.jpg',
          '/images/cards/CSV4C162.jpg',
          '/images/cards/CSV4C163.jpg',
        ],
      },
      {
        id: 'csv5',
        date: '2025.09.12',
        title: '黑晶炽诚',
        titleEn: 'CSV5 — Dark Crystal Passion',
        code: 'CSV5C',
        type: 'expansion',
        description: '朱&紫第五弹补充包，129+35张卡牌。',
        descriptionLong: '「黑晶炽诚」以暗属性和太晶化的融合为主题，收录了129+35张卡牌。包含了喷火龙ex SAR等高人气高价值卡牌。',
        image: '/images/history/sv5.png',
        cardCount: '129+35',
        features: ['喷火龙ex SAR', '暗属性主题', '高价值卡牌'],
        cardImages: [
          '/images/cards/CSV5C014.jpg',
          '/images/cards/CSV5C075.jpg',
          '/images/cards/CSV5C130.jpg',
          '/images/cards/CSV5C135.jpg',
          '/images/cards/CSV5C137.jpg',
          '/images/cards/CSV5C155.jpg',
          '/images/cards/CSV5C163.jpg',
          '/images/cards/CSV5C164.jpg',
        ],
      },
      {
        id: 'gem-pack-3',
        date: '2025.09.26',
        title: '宝石包 VOL.3',
        titleEn: 'Gem Pack VOL.3',
        code: 'CBB3C',
        type: 'gem-pack',
        description: '宝石包第三弹，约136张卡牌。',
        descriptionLong: '宝石包 VOL.3 收录约136张卡牌，继续提供高品质的收藏型闪卡。本弹包含了耿鬼、喵喵等经典宝可梦的全新AR插画。',
        image: '/images/poster-vol3-square.png',
        cardCount: '~136',
        features: ['耿鬼AR收录', '经典宝可梦新插画'],
        cardImages: [
          '/images/cards/CBB3C0207.jpg',
          '/images/cards/CBB3C0306.jpg',
          '/images/cards/CBB3C0307.jpg',
          '/images/cards/CBB3C0407.jpg',
          '/images/cards/CBB3C1107.jpg',
          '/images/cards/CBB3C1507.jpg',
          '/images/cards/CBB3C1607.jpg',
          '/images/cards/CBB3C1901.jpg',
          '/images/cards/CBB3C1904.jpg',
          '/images/cards/CBB3C2006.jpg',
        ],
      },
      {
        id: 'csv6',
        date: '2025.11.07',
        title: '真实玄虚',
        titleEn: 'CSV6 — Real Illusion',
        code: 'CSV6C',
        type: 'expansion',
        description: '朱&紫第六弹补充包，128+35张卡牌。',
        descriptionLong: '「真实玄虚」是朱&紫第六弹，以虚实交错为主题，收录128+35张卡牌。',
        image: '/images/history/sv6.png',
        cardCount: '128+35',
        features: ['虚实主题', '新ex宝可梦'],
        cardImages: [
          '/images/cards/CSV6C082.jpg',
          '/images/cards/CSV6C118.jpg',
          '/images/cards/CSV6C119.jpg',
          '/images/cards/CSV6C127.jpg',
          '/images/cards/CSV6C128.jpg',
          '/images/cards/CSV6C130.jpg',
          '/images/cards/CSV6C133.jpg',
          '/images/cards/CSV6C136.jpg',
          '/images/cards/CSV6C147.jpg',
          '/images/cards/CSV6C152.jpg',
          '/images/cards/CSV6C155.jpg',
          '/images/cards/CSV6C162.jpg',
        ],
      },
      {
        id: 'csv7',
        date: '2026.01.16',
        title: '利刃猛醒',
        titleEn: 'CSV7 — Sharp Awakening',
        code: 'CSV7C',
        type: 'expansion',
        description: '朱&紫第七弹，大型补充包，204+55张卡牌。',
        descriptionLong: '「利刃猛醒」是朱&紫系列的一个重要转折点，作为大型补充包收录了204+55张卡牌，几乎是普通补充包的1.5倍。\n\n大规模的卡牌收录意味着更丰富的策略选择和更多的收藏价值，包含了大量SAR和SR插画卡牌。',
        image: '/images/history/sv7.png',
        cardCount: '204+55',
        features: ['大型补充包', '259张卡牌', '大量SAR/SR'],
        cardImages: [
          '/images/cards/CSV7C021b.jpg',
          '/images/cards/CSV7C090.jpg',
          '/images/cards/CSV7C154.jpg',
          '/images/cards/CSV7C163.jpg',
          '/images/cards/CSV7C205.jpg',
          '/images/cards/CSV7C206.jpg',
          '/images/cards/CSV7C209.jpg',
          '/images/cards/CSV7C210.jpg',
          '/images/cards/CSV7C235.jpg',
          '/images/cards/CSV7C242.jpg',
          '/images/cards/CSV7C245.jpg',
          '/images/cards/CSV7C257.jpg',
        ],
      },
      {
        id: 'gem-pack-4',
        date: '2026.02.06',
        title: '宝石包 VOL.4',
        titleEn: 'Gem Pack VOL.4',
        code: 'CBB4C',
        type: 'gem-pack',
        description: '宝石包第四弹，196张卡牌。',
        descriptionLong: '宝石包 VOL.4 是迄今为止收录最多的宝石包，共196张卡牌。收录了烈焰猴、火斑喵、煤炭龟等人气宝可梦的全新AR插画，以及大量全新SR卡牌。',
        image: '/images/poster-vol4-square.png',
        cardCount: '196',
        features: ['196张卡牌', '烈焰猴/火斑喵AR', '大规模收录'],
        cardImages: [
          '/images/cards/CBB4C0101.jpg',
          '/images/cards/CBB4C0102.jpg',
          '/images/cards/CBB4C0103.jpg',
          '/images/cards/CBB4C0104.jpg',
          '/images/cards/CBB4C0105.jpg',
          '/images/cards/CBB4C0106.jpg',
          '/images/cards/CBB4C0107.jpg',
          '/images/cards/CBB4C0407.jpg',
          '/images/cards/CBB4C0607.jpg',
          '/images/cards/CBB4C0907.jpg',
          '/images/cards/CBB4C1407.jpg',
          '/images/cards/CBB4C1607.jpg',
          '/images/cards/CBB4C1907.jpg',
          '/images/cards/CBB4C2007.jpg',
          '/images/cards/CBB4C2307.jpg',
          '/images/cards/CBB4C2407.jpg',
        ],
      },
      {
        id: 'csv8',
        date: '2026.03.13',
        title: '璀璨诡幻',
        titleEn: 'CSV8 — Brilliant Phantasm',
        code: 'CSV8C',
        type: 'expansion',
        description: '朱&紫第八弹，大型补充包，207+57张卡牌。',
        descriptionLong: '「璀璨诡幻」是朱&紫系列的第八弹，延续了大型补充包的规模，收录207+57张卡牌。收录了美纳斯ex SAR等高价值卡牌，是目前最新的主系列补充包。',
        image: '/images/history/sv8.png',
        cardCount: '207+57',
        features: ['大型补充包', '美纳斯ex SAR', '264张卡牌'],
        cardImages: [
          '/images/cards/CSV8C244.jpg',
          '/images/cards/CSV8C255.jpg',
        ],
      },
      {
        id: 'gem-pack-5',
        date: '2026.04.24',
        title: '宝石包 VOL.5',
        titleEn: 'Gem Pack VOL.5',
        code: 'CBB5C',
        type: 'gem-pack',
        description: '宝石包第五弹，196张卡牌。最新发售！',
        descriptionLong: '宝石包 VOL.5 是最新发售的宝石包产品，收录196张卡牌。包含了船长皮卡丘AR、三合一磁怪SAR等高人气卡牌。\n\n作为宝石包系列的第五弹，延续了高品质闪卡的传统，是收藏和投资的热门选择。',
        image: '/images/poster-vol5-square.png',
        cardCount: '196',
        highlight: true,
        features: ['最新发售', '船长皮卡丘AR', '三合一磁怪SAR', '196张卡牌'],
        cardImages: [
          '/images/cards/CBB5C0107.jpg',
          '/images/cards/CBB5C0207.jpg',
          '/images/cards/CBB5C0307.jpg',
          '/images/cards/CBB5C1107.jpg',
          '/images/cards/CBB5C1207.jpg',
          '/images/cards/CBB5C1807.jpg',
          '/images/cards/CBB5C2207.jpg',
          '/images/cards/CBB5C2307.jpg',
          '/images/cards/CBB5C2407.jpg',
          '/images/cards/CBB5C2807.jpg',
        ],
      },
    ],
  },
]

/* Helper: find entry by id */
export function findEntry(id: string): { entry: TimelineEntry; era: TimelineEra } | null {
  for (const era of TIMELINE) {
    const entry = era.entries.find((e) => e.id === id)
    if (entry) return { entry, era }
  }
  return null
}

/* Helper: get all entry ids */
export function getAllEntryIds(): string[] {
  return TIMELINE.flatMap((era) => era.entries.map((e) => e.id))
}
