import type { PokemonCard, GemPack, PricePoint, Market } from './types'

// JPY to CNY conversion rate
export const JPY_TO_CNY = 0.04334

export const POKEMON_CARDS: PokemonCard[] = [
  // ─── テラスタルフェスex (SV8a) - Eevee Evolution Series ──────────
  {
    id: 'sv8a_217',
    nameJP: 'ブラッキーex',
    nameCN: '月亮伊布ex',
    nameEN: 'Umbreon ex',
    series: 'SV8a',
    cardNumber: '217',
    rarity: 'SAR',
    types: ['dark'],
    imageUrl: '/images/cards/umbreon-ex-217.png',
    priceJPY: 48300,
    priceCNY: Math.round(48300 * JPY_TO_CNY * 100) / 100,
    medianPriceJPY: 46000,
    lowestPriceJPY: 42000,
    priceChange24h: 5.2,
    availableOn: ['mercari', 'yahoo', 'ebay'],
    onSaleCount: 8,
    soldCount7d: 62,
    isHot: true,
    isBelowMedian: false,
    isNewListing: false,
    gradedAvailable: true,
    gradedPriceJPY: 80000,
    tags: ['eevee-series', 'dark', 'sar', 'premium', 'trending'],
    relatedIds: ['sv8a_212', 'sv8a_223', 'sv8a_211'],
  },
  {
    id: 'sv8a_212',
    nameJP: 'ニンフィアex',
    nameCN: '仙子伊布ex',
    nameEN: 'Sylveon ex',
    series: 'SV8a',
    cardNumber: '212',
    rarity: 'SAR',
    types: ['fairy'],
    imageUrl: '/images/cards/sylveon-ex-212.png',
    priceJPY: 18000,
    priceCNY: Math.round(18000 * JPY_TO_CNY * 100) / 100,
    medianPriceJPY: 17500,
    lowestPriceJPY: 15000,
    priceChange24h: 2.8,
    availableOn: ['mercari', 'yahoo', 'ebay'],
    onSaleCount: 12,
    soldCount7d: 45,
    isHot: true,
    isBelowMedian: false,
    isNewListing: false,
    gradedAvailable: true,
    gradedPriceJPY: 28500,
    tags: ['eevee-series', 'fairy', 'sar', 'popular'],
    relatedIds: ['sv8a_217', 'sv8a_223', 'sv8a_200'],
  },
  {
    id: 'sv8a_211',
    nameJP: 'エーフィex',
    nameCN: '太阳伊布ex',
    nameEN: 'Espeon ex',
    series: 'SV8a',
    cardNumber: '211',
    rarity: 'SAR',
    types: ['psychic'],
    imageUrl: '/images/cards/espeon-ex-211.png',
    priceJPY: 8800,
    priceCNY: Math.round(8800 * JPY_TO_CNY * 100) / 100,
    medianPriceJPY: 9200,
    lowestPriceJPY: 7500,
    priceChange24h: -1.5,
    availableOn: ['mercari', 'yahoo'],
    onSaleCount: 15,
    soldCount7d: 38,
    isHot: false,
    isBelowMedian: true,
    isNewListing: false,
    gradedAvailable: true,
    gradedPriceJPY: 17600,
    tags: ['eevee-series', 'psychic', 'sar'],
    relatedIds: ['sv8a_217', 'sv8a_212', 'sv8a_206'],
  },
  {
    id: 'sv8a_200',
    nameJP: 'リーフィアex',
    nameCN: '叶伊布ex',
    nameEN: 'Leafeon ex',
    series: 'SV8a',
    cardNumber: '200',
    rarity: 'SAR',
    types: ['grass'],
    imageUrl: '/images/cards/leafeon-ex-200.png',
    priceJPY: 8800,
    priceCNY: Math.round(8800 * JPY_TO_CNY * 100) / 100,
    medianPriceJPY: 9000,
    lowestPriceJPY: 7200,
    priceChange24h: -0.8,
    availableOn: ['mercari', 'yahoo'],
    onSaleCount: 14,
    soldCount7d: 35,
    isHot: false,
    isBelowMedian: true,
    isNewListing: false,
    gradedAvailable: false,
    tags: ['eevee-series', 'grass', 'sar'],
    relatedIds: ['sv8a_217', 'sv8a_212', 'sv8a_205'],
  },
  {
    id: 'sv8a_236',
    nameJP: 'ピカチュウex',
    nameCN: '皮卡丘ex',
    nameEN: 'Pikachu ex',
    series: 'SV8a',
    cardNumber: '236',
    rarity: 'SAR',
    types: ['electric'],
    imageUrl: '/images/cards/pikachu-ex-236.png',
    priceJPY: 6900,
    priceCNY: Math.round(6900 * JPY_TO_CNY * 100) / 100,
    medianPriceJPY: 7200,
    lowestPriceJPY: 5800,
    priceChange24h: 1.2,
    availableOn: ['mercari', 'yahoo', 'ebay', 'aliexpress'],
    onSaleCount: 25,
    soldCount7d: 85,
    isHot: true,
    isBelowMedian: true,
    isNewListing: false,
    gradedAvailable: true,
    gradedPriceJPY: 22000,
    tags: ['electric', 'sar', 'popular', 'top-seller'],
    relatedIds: ['me02_234', 'sv8a_217'],
  },
  {
    id: 'sv8a_205',
    nameJP: 'シャワーズex',
    nameCN: '水伊布ex',
    nameEN: 'Vaporeon ex',
    series: 'SV8a',
    cardNumber: '205',
    rarity: 'SAR',
    types: ['water'],
    imageUrl: '/images/cards/vaporeon-ex-205.png',
    priceJPY: 8200,
    priceCNY: Math.round(8200 * JPY_TO_CNY * 100) / 100,
    medianPriceJPY: 8500,
    lowestPriceJPY: 6800,
    priceChange24h: -0.5,
    availableOn: ['mercari', 'yahoo'],
    onSaleCount: 11,
    soldCount7d: 28,
    isHot: false,
    isBelowMedian: true,
    isNewListing: false,
    gradedAvailable: false,
    tags: ['eevee-series', 'water', 'sar'],
    relatedIds: ['sv8a_206', 'sv8a_202', 'sv8a_223'],
  },
  {
    id: 'sv8a_206',
    nameJP: 'グレイシアex',
    nameCN: '冰伊布ex',
    nameEN: 'Glaceon ex',
    series: 'SV8a',
    cardNumber: '206',
    rarity: 'SAR',
    types: ['water'],
    imageUrl: '/images/cards/glaceon-ex-206.png',
    priceJPY: 7500,
    priceCNY: Math.round(7500 * JPY_TO_CNY * 100) / 100,
    medianPriceJPY: 7800,
    lowestPriceJPY: 6200,
    priceChange24h: 0.3,
    availableOn: ['mercari', 'yahoo'],
    onSaleCount: 10,
    soldCount7d: 24,
    isHot: false,
    isBelowMedian: true,
    isNewListing: false,
    gradedAvailable: true,
    gradedPriceJPY: 16400,
    tags: ['eevee-series', 'water', 'sar'],
    relatedIds: ['sv8a_205', 'sv8a_202', 'sv8a_209'],
  },
  {
    id: 'sv8a_202',
    nameJP: 'ブースターex',
    nameCN: '火伊布ex',
    nameEN: 'Flareon ex',
    series: 'SV8a',
    cardNumber: '202',
    rarity: 'SAR',
    types: ['fire'],
    imageUrl: '/images/cards/flareon-ex-202.png',
    priceJPY: 7000,
    priceCNY: Math.round(7000 * JPY_TO_CNY * 100) / 100,
    medianPriceJPY: 7300,
    lowestPriceJPY: 5900,
    priceChange24h: -1.2,
    availableOn: ['mercari', 'yahoo'],
    onSaleCount: 13,
    soldCount7d: 30,
    isHot: false,
    isBelowMedian: true,
    isNewListing: false,
    gradedAvailable: true,
    gradedPriceJPY: 14900,
    tags: ['eevee-series', 'fire', 'sar'],
    relatedIds: ['sv8a_209', 'sv8a_200', 'sv8a_223'],
  },
  {
    id: 'sv8a_209',
    nameJP: 'サンダースex',
    nameCN: '雷伊布ex',
    nameEN: 'Jolteon ex',
    series: 'SV8a',
    cardNumber: '209',
    rarity: 'SAR',
    types: ['electric'],
    imageUrl: '/images/cards/jolteon-ex-209.png',
    priceJPY: 6100,
    priceCNY: Math.round(6100 * JPY_TO_CNY * 100) / 100,
    medianPriceJPY: 6500,
    lowestPriceJPY: 5200,
    priceChange24h: -0.9,
    availableOn: ['mercari', 'yahoo'],
    onSaleCount: 12,
    soldCount7d: 26,
    isHot: false,
    isBelowMedian: true,
    isNewListing: false,
    gradedAvailable: true,
    gradedPriceJPY: 15500,
    tags: ['eevee-series', 'electric', 'sar'],
    relatedIds: ['sv8a_236', 'sv8a_202', 'sv8a_206'],
  },
  {
    id: 'sv8a_223',
    nameJP: 'イーブイex',
    nameCN: '伊布ex',
    nameEN: 'Eevee ex',
    series: 'SV8a',
    cardNumber: '223',
    rarity: 'SAR',
    types: ['normal'],
    imageUrl: '/images/cards/eevee-ex-223.png',
    priceJPY: 4900,
    priceCNY: Math.round(4900 * JPY_TO_CNY * 100) / 100,
    medianPriceJPY: 5200,
    lowestPriceJPY: 4100,
    priceChange24h: -2.1,
    availableOn: ['mercari', 'yahoo', 'ebay'],
    onSaleCount: 18,
    soldCount7d: 52,
    isHot: true,
    isBelowMedian: true,
    isNewListing: false,
    gradedAvailable: true,
    gradedPriceJPY: 12700,
    tags: ['eevee-series', 'normal', 'sar', 'popular'],
    relatedIds: ['sv8a_217', 'sv8a_212', 'sv8a_236'],
  },
  // ─── MEGAドリームex (ME02) ──────────────────────────────────────
  {
    id: 'me02_240',
    nameJP: 'メガゲンガーex',
    nameCN: 'Mega耿鬼ex',
    nameEN: 'Mega Gengar ex',
    series: 'ME02',
    cardNumber: '240/193',
    rarity: 'SAR',
    types: ['ghost'],
    imageUrl: '/images/cards/mega-gengar-ex-sar.png',
    priceJPY: 48000,
    priceCNY: Math.round(48000 * JPY_TO_CNY * 100) / 100,
    medianPriceJPY: 45000,
    lowestPriceJPY: 40000,
    priceChange24h: 6.8,
    availableOn: ['mercari', 'yahoo', 'ebay'],
    onSaleCount: 5,
    soldCount7d: 48,
    isHot: true,
    isBelowMedian: false,
    isNewListing: true,
    gradedAvailable: false,
    tags: ['ghost', 'sar', 'premium', 'trending', 'mega'],
    relatedIds: ['me02_250', 'me02_234', 'me01_sar_charizard'],
  },
  {
    id: 'me02_234',
    nameJP: 'ピカチュウex',
    nameCN: '皮卡丘ex',
    nameEN: 'Pikachu ex',
    series: 'ME02',
    cardNumber: '234/193',
    rarity: 'SAR',
    types: ['electric'],
    imageUrl: '/images/cards/pikachu-ex-me02-sar.png',
    priceJPY: 40000,
    priceCNY: Math.round(40000 * JPY_TO_CNY * 100) / 100,
    medianPriceJPY: 38000,
    lowestPriceJPY: 34000,
    priceChange24h: 4.5,
    availableOn: ['mercari', 'yahoo', 'ebay'],
    onSaleCount: 4,
    soldCount7d: 55,
    isHot: true,
    isBelowMedian: false,
    isNewListing: true,
    gradedAvailable: false,
    tags: ['electric', 'sar', 'premium', 'trending', 'mega'],
    relatedIds: ['me02_240', 'sv8a_236', 'me02_250'],
  },
  {
    id: 'me02_250',
    nameJP: 'メガカイリューex',
    nameCN: 'Mega快龙ex',
    nameEN: 'Mega Dragonite ex',
    series: 'ME02',
    cardNumber: '250/193',
    rarity: 'MUR',
    types: ['dragon'],
    imageUrl: '/images/cards/mega-dragonite-ex-mur.png',
    priceJPY: 36000,
    priceCNY: Math.round(36000 * JPY_TO_CNY * 100) / 100,
    medianPriceJPY: 34000,
    lowestPriceJPY: 29000,
    priceChange24h: 3.2,
    availableOn: ['mercari', 'yahoo', 'ebay'],
    onSaleCount: 6,
    soldCount7d: 40,
    isHot: true,
    isBelowMedian: false,
    isNewListing: true,
    gradedAvailable: false,
    tags: ['dragon', 'mur', 'premium', 'trending', 'mega'],
    relatedIds: ['me02_240', 'me02_234', 'me02_mewtwo'],
  },
  {
    id: 'me02_mewtwo',
    nameJP: 'ロケット団のミュウツーex',
    nameCN: '火箭队的超梦ex',
    nameEN: "Team Rocket's Mewtwo ex",
    series: 'ME02',
    cardNumber: 'SAR',
    rarity: 'SAR',
    types: ['psychic'],
    imageUrl: '/images/cards/rockets-mewtwo-ex-sar.png',
    priceJPY: 19700,
    priceCNY: Math.round(19700 * JPY_TO_CNY * 100) / 100,
    medianPriceJPY: 20500,
    lowestPriceJPY: 17000,
    priceChange24h: -1.8,
    availableOn: ['mercari', 'yahoo', 'ebay'],
    onSaleCount: 9,
    soldCount7d: 35,
    isHot: true,
    isBelowMedian: true,
    isNewListing: true,
    gradedAvailable: false,
    tags: ['psychic', 'sar', 'premium', 'mega', 'team-rocket'],
    relatedIds: ['me02_240', 'me02_234', 'me02_zoroark'],
  },
  {
    id: 'me02_zoroark',
    nameJP: 'Nのゾロアークex',
    nameCN: 'N的索罗亚克ex',
    nameEN: "N's Zoroark ex",
    series: 'ME02',
    cardNumber: 'SAR',
    rarity: 'SAR',
    types: ['dark'],
    imageUrl: '/images/cards/ns-zoroark-ex-sar.png',
    priceJPY: 9200,
    priceCNY: Math.round(9200 * JPY_TO_CNY * 100) / 100,
    medianPriceJPY: 9500,
    lowestPriceJPY: 7800,
    priceChange24h: -0.5,
    availableOn: ['mercari', 'yahoo'],
    onSaleCount: 14,
    soldCount7d: 28,
    isHot: false,
    isBelowMedian: true,
    isNewListing: true,
    gradedAvailable: false,
    tags: ['dark', 'sar', 'mega', 'trainer'],
    relatedIds: ['me02_mewtwo', 'sv8a_217', 'me02_240'],
  },
  // ─── 幻炎の闘撃 (ME01) ─────────────────────────────────────────
  {
    id: 'me01_sar_charizard',
    nameJP: 'メガリザードンXex',
    nameCN: 'MegaX喷火龙ex',
    nameEN: 'Mega Charizard X ex',
    series: 'ME01',
    cardNumber: 'SAR',
    rarity: 'SAR',
    types: ['fire', 'dragon'],
    imageUrl: '/images/cards/mega-charizard-x-sar.png',
    priceJPY: 80000,
    priceCNY: Math.round(80000 * JPY_TO_CNY * 100) / 100,
    medianPriceJPY: 75000,
    lowestPriceJPY: 68000,
    priceChange24h: 8.5,
    availableOn: ['mercari', 'yahoo', 'ebay'],
    onSaleCount: 3,
    soldCount7d: 42,
    isHot: true,
    isBelowMedian: false,
    isNewListing: false,
    gradedAvailable: true,
    gradedPriceJPY: 160000,
    tags: ['fire', 'dragon', 'sar', 'premium', 'trending', 'top-seller', 'mega'],
    relatedIds: ['me01_mur_lucario', 'me01_mur_gardevoir', 'me02_240'],
  },
  {
    id: 'me01_mur_lucario',
    nameJP: 'メガルカリオex',
    nameCN: 'Mega路卡利欧ex',
    nameEN: 'Mega Lucario ex',
    series: 'ME01',
    cardNumber: 'MUR',
    rarity: 'MUR',
    types: ['fighting'],
    imageUrl: '/images/cards/mega-lucario-ex-mur.png',
    priceJPY: 62000,
    priceCNY: Math.round(62000 * JPY_TO_CNY * 100) / 100,
    medianPriceJPY: 60000,
    lowestPriceJPY: 52000,
    priceChange24h: 3.1,
    availableOn: ['mercari', 'yahoo', 'ebay'],
    onSaleCount: 4,
    soldCount7d: 30,
    isHot: true,
    isBelowMedian: false,
    isNewListing: false,
    gradedAvailable: true,
    gradedPriceJPY: 120000,
    tags: ['fighting', 'mur', 'premium', 'mega'],
    relatedIds: ['me01_sar_charizard', 'me01_mur_gardevoir', 'me02_250'],
  },
  {
    id: 'me01_mur_gardevoir',
    nameJP: 'メガサーナイトex',
    nameCN: 'Mega沙奈朵ex',
    nameEN: 'Mega Gardevoir ex',
    series: 'ME01',
    cardNumber: 'MUR',
    rarity: 'MUR',
    types: ['psychic', 'fairy'],
    imageUrl: '/images/cards/mega-gardevoir-ex-mur.png',
    priceJPY: 63000,
    priceCNY: Math.round(63000 * JPY_TO_CNY * 100) / 100,
    medianPriceJPY: 61000,
    lowestPriceJPY: 54000,
    priceChange24h: 2.5,
    availableOn: ['mercari', 'yahoo', 'ebay'],
    onSaleCount: 3,
    soldCount7d: 28,
    isHot: true,
    isBelowMedian: false,
    isNewListing: false,
    gradedAvailable: true,
    gradedPriceJPY: 125000,
    tags: ['psychic', 'fairy', 'mur', 'premium', 'mega'],
    relatedIds: ['me01_sar_charizard', 'me01_mur_lucario', 'me02_mewtwo'],
  },
  // ─── プリズマティックエボリューション (SV8pt5) ──────────────────
  {
    id: 'sv8pt5_161',
    nameJP: 'ブラッキーex',
    nameCN: '月亮伊布ex',
    nameEN: 'Umbreon ex',
    series: 'SV8pt5',
    cardNumber: '161/131',
    rarity: 'SIR',
    types: ['dark'],
    imageUrl: '/images/cards/umbreon-ex-pe-161.png',
    priceJPY: 168000,
    priceCNY: Math.round(168000 * JPY_TO_CNY * 100) / 100,
    medianPriceJPY: 160000,
    lowestPriceJPY: 145000,
    priceChange24h: 12.4,
    availableOn: ['mercari', 'yahoo', 'ebay'],
    onSaleCount: 2,
    soldCount7d: 35,
    isHot: true,
    isBelowMedian: false,
    isNewListing: false,
    gradedAvailable: true,
    gradedPriceJPY: 350000,
    tags: ['dark', 'sir', 'premium', 'trending', 'top-seller', 'chase-card'],
    relatedIds: ['sv8a_217', 'sv151_199', 'me01_sar_charizard'],
  },
  // ─── ポケモンカード151 (SV151) ─────────────────────────────────
  {
    id: 'sv151_199',
    nameJP: 'リザードンex',
    nameCN: '喷火龙ex',
    nameEN: 'Charizard ex',
    series: 'SV151',
    cardNumber: '199/165',
    rarity: 'SAR',
    types: ['fire'],
    imageUrl: '/images/cards/charizard-ex-151-199.png',
    priceJPY: 53500,
    priceCNY: Math.round(53500 * JPY_TO_CNY * 100) / 100,
    medianPriceJPY: 51000,
    lowestPriceJPY: 45000,
    priceChange24h: 4.8,
    availableOn: ['mercari', 'yahoo', 'ebay', 'aliexpress'],
    onSaleCount: 7,
    soldCount7d: 68,
    isHot: true,
    isBelowMedian: false,
    isNewListing: false,
    gradedAvailable: true,
    gradedPriceJPY: 120000,
    tags: ['fire', 'sar', 'premium', 'trending', 'top-seller', '151'],
    relatedIds: ['me01_sar_charizard', 'sv8pt5_161', 'me02_240'],
  },
]

// Simulated price history for charts (last 14 days)
export function getPriceHistory(cardId: string): PricePoint[] {
  const card = POKEMON_CARDS.find(c => c.id === cardId)
  if (!card) return []

  const now = new Date()
  const basePrice = card.medianPriceJPY
  const markets: Market[] = ['mercari', 'yahoo']

  return Array.from({ length: 14 }, (_, i) => {
    const date = new Date(now)
    date.setDate(date.getDate() - (13 - i))
    const variance = (Math.random() - 0.5) * 0.15
    const trend = i * 0.005 * (card.priceChange24h > 0 ? 1 : -1)
    const priceJPY = Math.round(basePrice * (1 + variance + trend))
    return {
      date: date.toISOString().split('T')[0],
      priceJPY,
      priceCNY: Math.round(priceJPY * JPY_TO_CNY * 100) / 100,
      market: markets[i % 2],
    }
  })
}

export function getCardById(id: string): PokemonCard | undefined {
  return POKEMON_CARDS.find(c => c.id === id)
}

export function getCardsByType(type: string): PokemonCard[] {
  return POKEMON_CARDS.filter(c => c.types.includes(type as any))
}

export function getCardsBySeries(series: string): PokemonCard[] {
  return POKEMON_CARDS.filter(c => c.series === series)
}

export function getHotCards(): PokemonCard[] {
  return POKEMON_CARDS.filter(c => c.isHot).sort((a, b) => b.soldCount7d - a.soldCount7d)
}

export function getDealsCards(): PokemonCard[] {
  return POKEMON_CARDS.filter(c => c.isBelowMedian).sort(
    (a, b) => (a.priceJPY / a.medianPriceJPY) - (b.priceJPY / b.medianPriceJPY)
  )
}

export function getNewListings(): PokemonCard[] {
  return POKEMON_CARDS.filter(c => c.isNewListing)
}
